package local:build;

interface init {
  init: func();
}

interface build {
  build: func() -> result<_, string>;
}

interface register {
  register: func(name: string) -> result<_, string>;
}

world facade {
  export init;
  export build;
  export register;
}
