name: builders
on: [push]

jobs:
  linux-kernel-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build image
        run: |
          docker buildx create \
            --use \
            --name builder \
            --platform linux/amd64 \
            --driver docker-container

          docker buildx build \
            -f Dockerfile.linux-kernel \
            -t ghcr.io/dfinity/linux-kernel-builder:${{ github.sha }} \
            --platform linux/amd64 \
            --build-arg SOURCE_DATE_EPOCH=0 \
            --output type=docker,dest=archive.tar,rewrite-timestamp=true \
                .
      
    #   - name: Login to container registry
    #     run: |
    #       docker login \
    #         -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} \
    #         -p ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} \
    #         ghcr.io
      
    #   - name: Publish docker image
    #     run: docker push ghcr.io/dfinity/linux-kernel-builder:${{ github.sha }}
