name: release

permissions:
  contents: write

on:
  push:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh release list
